name: Compare JSON Files Before Merge

on:
  pull_request:
    branches:
      - int
      - main

    types:
      - opened
      - synchronize

jobs:
  diff_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Latest Branches
        run: |
          git fetch origin ${{ github.base_ref }} ${{ github.head_ref }}

      - name: Create Diff Directory
        run: |
          mkdir -p ./changes/git-diff

      - name: Compare JSON Files in repo-shopify-data
        run: |
          DIFF_FILE="./changes/git-diff/changes.diff"
          git diff origin/${{ github.base_ref }}..origin/${{ github.head_ref }} -- 'repo-shopify-data/*.json' > $DIFF_FILE
          
          if [ ! -s $DIFF_FILE ]; then
            echo "✅ No JSON files changed in repo-shopify-data" > $DIFF_FILE
          fi
          
          cat $DIFF_FILE

      - name: Switch to Target Branch (`int`) and Apply Changes
        run: |
          git checkout ${{ github.base_ref }}  # Switch to `int`
          git pull origin ${{ github.base_ref }}

          # ✅ Fix: Set Git User Identity
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add ./changes/git-diff/changes.diff
          git status  # Debugging: Show Git status

          if git diff --cached --quiet; then
            echo "✅ No new changes detected. Skipping commit."
          else
            git commit -m "Update changes.diff with JSON file differences"
            git push origin ${{ github.base_ref }}
          fi
