name: Compare JSON Files After Merge to `int`

on:
  push:
    branches:
      - int  # ✅ Runs only when a new commit is pushed to `int`

jobs:
  diff_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Latest Branches
        run: |
          git fetch origin main  # Fetch latest `main`
          git fetch origin int  # Fetch latest `int`

      - name: Create Diff Directory
        run: |
          mkdir -p ./changes/git-diff

      - name: Compare JSON Files in repo-shopify-data (int vs main)
        run: |
          DIFF_FILE="./changes/git-diff/changes.diff"

          # ✅ Compare `int` against `main`
          git diff origin/main..origin/int -- 'repo-shopify-data/*.json' > $DIFF_FILE

          if [ ! -s $DIFF_FILE ]; then
            echo "✅ No JSON files changed between `int` and `main`" > $DIFF_FILE
          fi

          cat $DIFF_FILE  # Show diff output for debugging

      - name: Upload Diff Report
        uses: actions/upload-artifact@v4
        with:
          name: json-diff-report
          path: ./changes/git-diff/changes.diff

      - name: Commit and Push Diff File to `int`
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add ./changes/git-diff/changes.diff
          git status  # Debugging: Show Git status

          # ✅ Prevent empty commits
          if git diff --cached --quiet; then
            echo "✅ No new changes detected. Skipping commit."
          else
            git commit -m "Update changes.diff with JSON file differences after merging into int"
            git push origin int || echo "⚠️ Warning: Git push failed. Check permissions."
          fi
