name: Compare JSON Files on PR

on:
  pull_request:
    branches:
      - int  # Runs only when merging into 'int'

jobs:
  diff_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history is available

      - name: Fetch Latest Branches
        run: |
          git fetch origin ${{ github.base_ref }} ${{ github.head_ref }}

      - name: Create Diff Directory
        run: |
          mkdir -p ./changes/git-diff

      - name: Compare JSON Files in repo-shopify-data
        run: |
          DIFF_FILE="./changes/git-diff/changes.diff"
          git diff origin/${{ github.base_ref }}..origin/${{ github.head_ref }} -- 'repo-shopify-data/*.json' > $DIFF_FILE

          if [ -s $DIFF_FILE ]; then
            echo "✅ JSON files changed:"
            cat $DIFF_FILE
          else
            echo "✅ No JSON files changed in repo-shopify-data" > $DIFF_FILE
          fi

      - name: Upload Diff Report
        uses: actions/upload-artifact@v4
        with:
          name: json-diff-report
          path: ./changes/git-diff/changes.diff