name: Compare JSON Files on PR

on:
  pull_request:
    branches:
      - int  # Runs only when merging into 'int'

jobs:
  diff_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Latest Branches
        run: |
          git fetch origin ${{ github.base_ref }} ${{ github.head_ref }}

      - name: Create Diff Directory
        run: |
          mkdir -p ./changes/git-diff

      - name: Compare JSON Files in repo-shopify-data
        run: |
          DIFF_FILE="./changes/git-diff/changes.diff"
          
          # Run git diff and save output
          git diff origin/${{ github.base_ref }}..origin/${{ github.head_ref }} -- 'repo-shopify-data/*.json' > $DIFF_FILE
          
          # Ensure the file is not empty, otherwise, Git won't track it
          if [ ! -s $DIFF_FILE ]; then
            echo "✅ No JSON files changed in repo-shopify-data" > $DIFF_FILE
          fi
          
          cat $DIFF_FILE  # Show the diff output for debugging
          
          # Stash changes to persist them across branch switch
          git add $DIFF_FILE
          git stash push -m "Saving changes.diff for later use"

      - name: Switch to Target Branch (`int`) and Apply Changes
        run: |
          git checkout ${{ github.base_ref }}  # Switch to `int`
          git pull origin ${{ github.base_ref }}  # Ensure latest changes

          git stash pop || echo "✅ No stashed changes to apply"

          git add ./changes/git-diff/changes.diff
          git status  # Debugging: Show Git status

          if git diff --cached --quiet; then
            echo "✅ No new changes detected. Skipping commit."
          else
            git commit -m "Update changes.diff with JSON file differences"
            git push origin ${{ github.base_ref }}
          fi
